if(EXISTS "/home/jgreninger/Work/DTLSv1p3/tests/security/dtls_security_tests[1]_tests.cmake")
  include("/home/jgreninger/Work/DTLSv1p3/tests/security/dtls_security_tests[1]_tests.cmake")
else()
  add_test(dtls_security_tests_NOT_BUILT dtls_security_tests_NOT_BUILT)
endif()
