if(EXISTS "/home/jgreninger/Work/DTLSv1p3/tests/security/dtls_advanced_fuzzing_tests[1]_tests.cmake")
  include("/home/jgreninger/Work/DTLSv1p3/tests/security/dtls_advanced_fuzzing_tests[1]_tests.cmake")
else()
  add_test(dtls_advanced_fuzzing_tests_NOT_BUILT dtls_advanced_fuzzing_tests_NOT_BUILT)
endif()
