# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jgreninger/Work/DTLSv1p3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jgreninger/Work/DTLSv1p3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/jgreninger/Work/DTLSv1p3/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"examples\" \"examples-doc\" \"examples-src\" \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jgreninger/Work/DTLSv1p3/CMakeFiles /home/jgreninger/Work/DTLSv1p3//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jgreninger/Work/DTLSv1p3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named dtlsv13

# Build rule for target.
dtlsv13: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtlsv13
.PHONY : dtlsv13

# fast build rule for target.
dtlsv13/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/dtlsv13.dir/build.make src/CMakeFiles/dtlsv13.dir/build
.PHONY : dtlsv13/fast

#=============================================================================
# Target rules for targets named dtls_test_infrastructure

# Build rule for target.
dtls_test_infrastructure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_test_infrastructure
.PHONY : dtls_test_infrastructure

# fast build rule for target.
dtls_test_infrastructure/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/dtls_test_infrastructure.dir/build.make tests/CMakeFiles/dtls_test_infrastructure.dir/build
.PHONY : dtls_test_infrastructure/fast

#=============================================================================
# Target rules for targets named dtls_protocol_test

# Build rule for target.
dtls_protocol_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_protocol_test
.PHONY : dtls_protocol_test

# fast build rule for target.
dtls_protocol_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/dtls_protocol_test.dir/build.make tests/CMakeFiles/dtls_protocol_test.dir/build
.PHONY : dtls_protocol_test/fast

#=============================================================================
# Target rules for targets named dtls_crypto_test

# Build rule for target.
dtls_crypto_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_crypto_test
.PHONY : dtls_crypto_test

# fast build rule for target.
dtls_crypto_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/dtls_crypto_test.dir/build.make tests/CMakeFiles/dtls_crypto_test.dir/build
.PHONY : dtls_crypto_test/fast

#=============================================================================
# Target rules for targets named dtls_connection_test

# Build rule for target.
dtls_connection_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_connection_test
.PHONY : dtls_connection_test

# fast build rule for target.
dtls_connection_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/dtls_connection_test.dir/build.make tests/CMakeFiles/dtls_connection_test.dir/build
.PHONY : dtls_connection_test/fast

#=============================================================================
# Target rules for targets named dtls_integration_test

# Build rule for target.
dtls_integration_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_integration_test
.PHONY : dtls_integration_test

# fast build rule for target.
dtls_integration_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/dtls_integration_test.dir/build.make tests/CMakeFiles/dtls_integration_test.dir/build
.PHONY : dtls_integration_test/fast

#=============================================================================
# Target rules for targets named dtls_performance_test

# Build rule for target.
dtls_performance_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_performance_test
.PHONY : dtls_performance_test

# fast build rule for target.
dtls_performance_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/dtls_performance_test.dir/build.make tests/CMakeFiles/dtls_performance_test.dir/build
.PHONY : dtls_performance_test/fast

#=============================================================================
# Target rules for targets named dtls_security_test

# Build rule for target.
dtls_security_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_security_test
.PHONY : dtls_security_test

# fast build rule for target.
dtls_security_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/dtls_security_test.dir/build.make tests/CMakeFiles/dtls_security_test.dir/build
.PHONY : dtls_security_test/fast

#=============================================================================
# Target rules for targets named dtls_reliability_test

# Build rule for target.
dtls_reliability_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_reliability_test
.PHONY : dtls_reliability_test

# fast build rule for target.
dtls_reliability_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/dtls_reliability_test.dir/build.make tests/CMakeFiles/dtls_reliability_test.dir/build
.PHONY : dtls_reliability_test/fast

#=============================================================================
# Target rules for targets named dtls_interop_test

# Build rule for target.
dtls_interop_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_interop_test
.PHONY : dtls_interop_test

# fast build rule for target.
dtls_interop_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/dtls_interop_test.dir/build.make tests/CMakeFiles/dtls_interop_test.dir/build
.PHONY : dtls_interop_test/fast

#=============================================================================
# Target rules for targets named run_all_tests

# Build rule for target.
run_all_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_all_tests
.PHONY : run_all_tests

# fast build rule for target.
run_all_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/run_all_tests.dir/build.make tests/CMakeFiles/run_all_tests.dir/build
.PHONY : run_all_tests/fast

#=============================================================================
# Target rules for targets named run_protocol_tests

# Build rule for target.
run_protocol_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_protocol_tests
.PHONY : run_protocol_tests

# fast build rule for target.
run_protocol_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/run_protocol_tests.dir/build.make tests/CMakeFiles/run_protocol_tests.dir/build
.PHONY : run_protocol_tests/fast

#=============================================================================
# Target rules for targets named run_crypto_tests

# Build rule for target.
run_crypto_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_crypto_tests
.PHONY : run_crypto_tests

# fast build rule for target.
run_crypto_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/run_crypto_tests.dir/build.make tests/CMakeFiles/run_crypto_tests.dir/build
.PHONY : run_crypto_tests/fast

#=============================================================================
# Target rules for targets named run_connection_tests

# Build rule for target.
run_connection_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_connection_tests
.PHONY : run_connection_tests

# fast build rule for target.
run_connection_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/run_connection_tests.dir/build.make tests/CMakeFiles/run_connection_tests.dir/build
.PHONY : run_connection_tests/fast

#=============================================================================
# Target rules for targets named run_integration_tests

# Build rule for target.
run_integration_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_integration_tests
.PHONY : run_integration_tests

# fast build rule for target.
run_integration_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/run_integration_tests.dir/build.make tests/CMakeFiles/run_integration_tests.dir/build
.PHONY : run_integration_tests/fast

#=============================================================================
# Target rules for targets named run_performance_tests

# Build rule for target.
run_performance_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_performance_tests
.PHONY : run_performance_tests

# fast build rule for target.
run_performance_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/run_performance_tests.dir/build.make tests/CMakeFiles/run_performance_tests.dir/build
.PHONY : run_performance_tests/fast

#=============================================================================
# Target rules for targets named run_security_tests

# Build rule for target.
run_security_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_security_tests
.PHONY : run_security_tests

# fast build rule for target.
run_security_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/run_security_tests.dir/build.make tests/CMakeFiles/run_security_tests.dir/build
.PHONY : run_security_tests/fast

#=============================================================================
# Target rules for targets named run_reliability_tests

# Build rule for target.
run_reliability_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_reliability_tests
.PHONY : run_reliability_tests

# fast build rule for target.
run_reliability_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/run_reliability_tests.dir/build.make tests/CMakeFiles/run_reliability_tests.dir/build
.PHONY : run_reliability_tests/fast

#=============================================================================
# Target rules for targets named run_interop_tests

# Build rule for target.
run_interop_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_interop_tests
.PHONY : run_interop_tests

# fast build rule for target.
run_interop_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/run_interop_tests.dir/build.make tests/CMakeFiles/run_interop_tests.dir/build
.PHONY : run_interop_tests/fast

#=============================================================================
# Target rules for targets named test_coverage

# Build rule for target.
test_coverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_coverage
.PHONY : test_coverage

# fast build rule for target.
test_coverage/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_coverage.dir/build.make tests/CMakeFiles/test_coverage.dir/build
.PHONY : test_coverage/fast

#=============================================================================
# Target rules for targets named test_memcheck

# Build rule for target.
test_memcheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_memcheck
.PHONY : test_memcheck

# fast build rule for target.
test_memcheck/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_memcheck.dir/build.make tests/CMakeFiles/test_memcheck.dir/build
.PHONY : test_memcheck/fast

#=============================================================================
# Target rules for targets named test_tsan

# Build rule for target.
test_tsan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_tsan
.PHONY : test_tsan

# fast build rule for target.
test_tsan/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_tsan.dir/build.make tests/CMakeFiles/test_tsan.dir/build
.PHONY : test_tsan/fast

#=============================================================================
# Target rules for targets named test_asan

# Build rule for target.
test_asan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_asan
.PHONY : test_asan

# fast build rule for target.
test_asan/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_asan.dir/build.make tests/CMakeFiles/test_asan.dir/build
.PHONY : test_asan/fast

#=============================================================================
# Target rules for targets named run_performance_benchmarks

# Build rule for target.
run_performance_benchmarks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_performance_benchmarks
.PHONY : run_performance_benchmarks

# fast build rule for target.
run_performance_benchmarks/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/run_performance_benchmarks.dir/build.make tests/CMakeFiles/run_performance_benchmarks.dir/build
.PHONY : run_performance_benchmarks/fast

#=============================================================================
# Target rules for targets named run_prd_validation

# Build rule for target.
run_prd_validation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_prd_validation
.PHONY : run_prd_validation

# fast build rule for target.
run_prd_validation/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/run_prd_validation.dir/build.make tests/CMakeFiles/run_prd_validation.dir/build
.PHONY : run_prd_validation/fast

#=============================================================================
# Target rules for targets named run_performance_regression

# Build rule for target.
run_performance_regression: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_performance_regression
.PHONY : run_performance_regression

# fast build rule for target.
run_performance_regression/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/run_performance_regression.dir/build.make tests/CMakeFiles/run_performance_regression.dir/build
.PHONY : run_performance_regression/fast

#=============================================================================
# Target rules for targets named performance_summary

# Build rule for target.
performance_summary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 performance_summary
.PHONY : performance_summary

# fast build rule for target.
performance_summary/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/performance_summary.dir/build.make tests/CMakeFiles/performance_summary.dir/build
.PHONY : performance_summary/fast

#=============================================================================
# Target rules for targets named test_report

# Build rule for target.
test_report: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_report
.PHONY : test_report

# fast build rule for target.
test_report/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_report.dir/build.make tests/CMakeFiles/test_report.dir/build
.PHONY : test_report/fast

#=============================================================================
# Target rules for targets named dtls_interop_framework

# Build rule for target.
dtls_interop_framework: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_interop_framework
.PHONY : dtls_interop_framework

# fast build rule for target.
dtls_interop_framework/fast:
	$(MAKE) $(MAKESILENT) -f tests/interoperability/CMakeFiles/dtls_interop_framework.dir/build.make tests/interoperability/CMakeFiles/dtls_interop_framework.dir/build
.PHONY : dtls_interop_framework/fast

#=============================================================================
# Target rules for targets named dtls_interop_tests

# Build rule for target.
dtls_interop_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_interop_tests
.PHONY : dtls_interop_tests

# fast build rule for target.
dtls_interop_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/interoperability/CMakeFiles/dtls_interop_tests.dir/build.make tests/interoperability/CMakeFiles/dtls_interop_tests.dir/build
.PHONY : dtls_interop_tests/fast

#=============================================================================
# Target rules for targets named interop_quick

# Build rule for target.
interop_quick: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 interop_quick
.PHONY : interop_quick

# fast build rule for target.
interop_quick/fast:
	$(MAKE) $(MAKESILENT) -f tests/interoperability/CMakeFiles/interop_quick.dir/build.make tests/interoperability/CMakeFiles/interop_quick.dir/build
.PHONY : interop_quick/fast

#=============================================================================
# Target rules for targets named interop_full

# Build rule for target.
interop_full: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 interop_full
.PHONY : interop_full

# fast build rule for target.
interop_full/fast:
	$(MAKE) $(MAKESILENT) -f tests/interoperability/CMakeFiles/interop_full.dir/build.make tests/interoperability/CMakeFiles/interop_full.dir/build
.PHONY : interop_full/fast

#=============================================================================
# Target rules for targets named interop_perf

# Build rule for target.
interop_perf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 interop_perf
.PHONY : interop_perf

# fast build rule for target.
interop_perf/fast:
	$(MAKE) $(MAKESILENT) -f tests/interoperability/CMakeFiles/interop_perf.dir/build.make tests/interoperability/CMakeFiles/interop_perf.dir/build
.PHONY : interop_perf/fast

#=============================================================================
# Target rules for targets named interop_report

# Build rule for target.
interop_report: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 interop_report
.PHONY : interop_report

# fast build rule for target.
interop_report/fast:
	$(MAKE) $(MAKESILENT) -f tests/interoperability/CMakeFiles/interop_report.dir/build.make tests/interoperability/CMakeFiles/interop_report.dir/build
.PHONY : interop_report/fast

#=============================================================================
# Target rules for targets named dtls_security_tests

# Build rule for target.
dtls_security_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_security_tests
.PHONY : dtls_security_tests

# fast build rule for target.
dtls_security_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/dtls_security_tests.dir/build.make tests/security/CMakeFiles/dtls_security_tests.dir/build
.PHONY : dtls_security_tests/fast

#=============================================================================
# Target rules for targets named dtls_rate_limiter_tests

# Build rule for target.
dtls_rate_limiter_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_rate_limiter_tests
.PHONY : dtls_rate_limiter_tests

# fast build rule for target.
dtls_rate_limiter_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/dtls_rate_limiter_tests.dir/build.make tests/security/CMakeFiles/dtls_rate_limiter_tests.dir/build
.PHONY : dtls_rate_limiter_tests/fast

#=============================================================================
# Target rules for targets named dtls_attack_resilience_tests

# Build rule for target.
dtls_attack_resilience_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_attack_resilience_tests
.PHONY : dtls_attack_resilience_tests

# fast build rule for target.
dtls_attack_resilience_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/dtls_attack_resilience_tests.dir/build.make tests/security/CMakeFiles/dtls_attack_resilience_tests.dir/build
.PHONY : dtls_attack_resilience_tests/fast

#=============================================================================
# Target rules for targets named dtls_timing_attack_tests

# Build rule for target.
dtls_timing_attack_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_timing_attack_tests
.PHONY : dtls_timing_attack_tests

# fast build rule for target.
dtls_timing_attack_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/dtls_timing_attack_tests.dir/build.make tests/security/CMakeFiles/dtls_timing_attack_tests.dir/build
.PHONY : dtls_timing_attack_tests/fast

#=============================================================================
# Target rules for targets named dtls_timing_attack_tests_simple

# Build rule for target.
dtls_timing_attack_tests_simple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_timing_attack_tests_simple
.PHONY : dtls_timing_attack_tests_simple

# fast build rule for target.
dtls_timing_attack_tests_simple/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/dtls_timing_attack_tests_simple.dir/build.make tests/security/CMakeFiles/dtls_timing_attack_tests_simple.dir/build
.PHONY : dtls_timing_attack_tests_simple/fast

#=============================================================================
# Target rules for targets named dtls_basic_timing_tests

# Build rule for target.
dtls_basic_timing_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_basic_timing_tests
.PHONY : dtls_basic_timing_tests

# fast build rule for target.
dtls_basic_timing_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/dtls_basic_timing_tests.dir/build.make tests/security/CMakeFiles/dtls_basic_timing_tests.dir/build
.PHONY : dtls_basic_timing_tests/fast

#=============================================================================
# Target rules for targets named dtls_side_channel_tests

# Build rule for target.
dtls_side_channel_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_side_channel_tests
.PHONY : dtls_side_channel_tests

# fast build rule for target.
dtls_side_channel_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/dtls_side_channel_tests.dir/build.make tests/security/CMakeFiles/dtls_side_channel_tests.dir/build
.PHONY : dtls_side_channel_tests/fast

#=============================================================================
# Target rules for targets named dtls_enhanced_side_channel_tests

# Build rule for target.
dtls_enhanced_side_channel_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_enhanced_side_channel_tests
.PHONY : dtls_enhanced_side_channel_tests

# fast build rule for target.
dtls_enhanced_side_channel_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/dtls_enhanced_side_channel_tests.dir/build.make tests/security/CMakeFiles/dtls_enhanced_side_channel_tests.dir/build
.PHONY : dtls_enhanced_side_channel_tests/fast

#=============================================================================
# Target rules for targets named dtls_simple_side_channel_tests

# Build rule for target.
dtls_simple_side_channel_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_simple_side_channel_tests
.PHONY : dtls_simple_side_channel_tests

# fast build rule for target.
dtls_simple_side_channel_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/dtls_simple_side_channel_tests.dir/build.make tests/security/CMakeFiles/dtls_simple_side_channel_tests.dir/build
.PHONY : dtls_simple_side_channel_tests/fast

#=============================================================================
# Target rules for targets named dtls_basic_side_channel_tests

# Build rule for target.
dtls_basic_side_channel_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_basic_side_channel_tests
.PHONY : dtls_basic_side_channel_tests

# fast build rule for target.
dtls_basic_side_channel_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/dtls_basic_side_channel_tests.dir/build.make tests/security/CMakeFiles/dtls_basic_side_channel_tests.dir/build
.PHONY : dtls_basic_side_channel_tests/fast

#=============================================================================
# Target rules for targets named dtls_protocol_fuzzing_tests

# Build rule for target.
dtls_protocol_fuzzing_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_protocol_fuzzing_tests
.PHONY : dtls_protocol_fuzzing_tests

# fast build rule for target.
dtls_protocol_fuzzing_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/dtls_protocol_fuzzing_tests.dir/build.make tests/security/CMakeFiles/dtls_protocol_fuzzing_tests.dir/build
.PHONY : dtls_protocol_fuzzing_tests/fast

#=============================================================================
# Target rules for targets named dtls_advanced_fuzzing_tests

# Build rule for target.
dtls_advanced_fuzzing_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_advanced_fuzzing_tests
.PHONY : dtls_advanced_fuzzing_tests

# fast build rule for target.
dtls_advanced_fuzzing_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/dtls_advanced_fuzzing_tests.dir/build.make tests/security/CMakeFiles/dtls_advanced_fuzzing_tests.dir/build
.PHONY : dtls_advanced_fuzzing_tests/fast

#=============================================================================
# Target rules for targets named dtls_message_fuzzing_tests

# Build rule for target.
dtls_message_fuzzing_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_message_fuzzing_tests
.PHONY : dtls_message_fuzzing_tests

# fast build rule for target.
dtls_message_fuzzing_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/dtls_message_fuzzing_tests.dir/build.make tests/security/CMakeFiles/dtls_message_fuzzing_tests.dir/build
.PHONY : dtls_message_fuzzing_tests/fast

#=============================================================================
# Target rules for targets named dtls_attack_simulation_tests

# Build rule for target.
dtls_attack_simulation_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_attack_simulation_tests
.PHONY : dtls_attack_simulation_tests

# fast build rule for target.
dtls_attack_simulation_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/dtls_attack_simulation_tests.dir/build.make tests/security/CMakeFiles/dtls_attack_simulation_tests.dir/build
.PHONY : dtls_attack_simulation_tests/fast

#=============================================================================
# Target rules for targets named comprehensive_security_validation

# Build rule for target.
comprehensive_security_validation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 comprehensive_security_validation
.PHONY : comprehensive_security_validation

# fast build rule for target.
comprehensive_security_validation/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/comprehensive_security_validation.dir/build.make tests/security/CMakeFiles/comprehensive_security_validation.dir/build
.PHONY : comprehensive_security_validation/fast

#=============================================================================
# Target rules for targets named security_report_generator

# Build rule for target.
security_report_generator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 security_report_generator
.PHONY : security_report_generator

# fast build rule for target.
security_report_generator/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/security_report_generator.dir/build.make tests/security/CMakeFiles/security_report_generator.dir/build
.PHONY : security_report_generator/fast

#=============================================================================
# Target rules for targets named security_tests_basic

# Build rule for target.
security_tests_basic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 security_tests_basic
.PHONY : security_tests_basic

# fast build rule for target.
security_tests_basic/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/security_tests_basic.dir/build.make tests/security/CMakeFiles/security_tests_basic.dir/build
.PHONY : security_tests_basic/fast

#=============================================================================
# Target rules for targets named rate_limiter_tests

# Build rule for target.
rate_limiter_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rate_limiter_tests
.PHONY : rate_limiter_tests

# fast build rule for target.
rate_limiter_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/rate_limiter_tests.dir/build.make tests/security/CMakeFiles/rate_limiter_tests.dir/build
.PHONY : rate_limiter_tests/fast

#=============================================================================
# Target rules for targets named attack_resilience_tests

# Build rule for target.
attack_resilience_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 attack_resilience_tests
.PHONY : attack_resilience_tests

# fast build rule for target.
attack_resilience_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/attack_resilience_tests.dir/build.make tests/security/CMakeFiles/attack_resilience_tests.dir/build
.PHONY : attack_resilience_tests/fast

#=============================================================================
# Target rules for targets named timing_attack_tests

# Build rule for target.
timing_attack_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 timing_attack_tests
.PHONY : timing_attack_tests

# fast build rule for target.
timing_attack_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/timing_attack_tests.dir/build.make tests/security/CMakeFiles/timing_attack_tests.dir/build
.PHONY : timing_attack_tests/fast

#=============================================================================
# Target rules for targets named side_channel_tests

# Build rule for target.
side_channel_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 side_channel_tests
.PHONY : side_channel_tests

# fast build rule for target.
side_channel_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/side_channel_tests.dir/build.make tests/security/CMakeFiles/side_channel_tests.dir/build
.PHONY : side_channel_tests/fast

#=============================================================================
# Target rules for targets named enhanced_side_channel_tests

# Build rule for target.
enhanced_side_channel_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 enhanced_side_channel_tests
.PHONY : enhanced_side_channel_tests

# fast build rule for target.
enhanced_side_channel_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/enhanced_side_channel_tests.dir/build.make tests/security/CMakeFiles/enhanced_side_channel_tests.dir/build
.PHONY : enhanced_side_channel_tests/fast

#=============================================================================
# Target rules for targets named basic_side_channel_tests

# Build rule for target.
basic_side_channel_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 basic_side_channel_tests
.PHONY : basic_side_channel_tests

# fast build rule for target.
basic_side_channel_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/basic_side_channel_tests.dir/build.make tests/security/CMakeFiles/basic_side_channel_tests.dir/build
.PHONY : basic_side_channel_tests/fast

#=============================================================================
# Target rules for targets named protocol_fuzzing_tests

# Build rule for target.
protocol_fuzzing_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 protocol_fuzzing_tests
.PHONY : protocol_fuzzing_tests

# fast build rule for target.
protocol_fuzzing_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/protocol_fuzzing_tests.dir/build.make tests/security/CMakeFiles/protocol_fuzzing_tests.dir/build
.PHONY : protocol_fuzzing_tests/fast

#=============================================================================
# Target rules for targets named advanced_fuzzing_tests

# Build rule for target.
advanced_fuzzing_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 advanced_fuzzing_tests
.PHONY : advanced_fuzzing_tests

# fast build rule for target.
advanced_fuzzing_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/advanced_fuzzing_tests.dir/build.make tests/security/CMakeFiles/advanced_fuzzing_tests.dir/build
.PHONY : advanced_fuzzing_tests/fast

#=============================================================================
# Target rules for targets named message_fuzzing_tests

# Build rule for target.
message_fuzzing_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 message_fuzzing_tests
.PHONY : message_fuzzing_tests

# fast build rule for target.
message_fuzzing_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/message_fuzzing_tests.dir/build.make tests/security/CMakeFiles/message_fuzzing_tests.dir/build
.PHONY : message_fuzzing_tests/fast

#=============================================================================
# Target rules for targets named attack_simulation_tests

# Build rule for target.
attack_simulation_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 attack_simulation_tests
.PHONY : attack_simulation_tests

# fast build rule for target.
attack_simulation_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/attack_simulation_tests.dir/build.make tests/security/CMakeFiles/attack_simulation_tests.dir/build
.PHONY : attack_simulation_tests/fast

#=============================================================================
# Target rules for targets named security_tests_comprehensive

# Build rule for target.
security_tests_comprehensive: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 security_tests_comprehensive
.PHONY : security_tests_comprehensive

# fast build rule for target.
security_tests_comprehensive/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/security_tests_comprehensive.dir/build.make tests/security/CMakeFiles/security_tests_comprehensive.dir/build
.PHONY : security_tests_comprehensive/fast

#=============================================================================
# Target rules for targets named security_tests_quick

# Build rule for target.
security_tests_quick: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 security_tests_quick
.PHONY : security_tests_quick

# fast build rule for target.
security_tests_quick/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/security_tests_quick.dir/build.make tests/security/CMakeFiles/security_tests_quick.dir/build
.PHONY : security_tests_quick/fast

#=============================================================================
# Target rules for targets named security_tests_attack_simulation

# Build rule for target.
security_tests_attack_simulation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 security_tests_attack_simulation
.PHONY : security_tests_attack_simulation

# fast build rule for target.
security_tests_attack_simulation/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/security_tests_attack_simulation.dir/build.make tests/security/CMakeFiles/security_tests_attack_simulation.dir/build
.PHONY : security_tests_attack_simulation/fast

#=============================================================================
# Target rules for targets named security_tests_fuzzing

# Build rule for target.
security_tests_fuzzing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 security_tests_fuzzing
.PHONY : security_tests_fuzzing

# fast build rule for target.
security_tests_fuzzing/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/security_tests_fuzzing.dir/build.make tests/security/CMakeFiles/security_tests_fuzzing.dir/build
.PHONY : security_tests_fuzzing/fast

#=============================================================================
# Target rules for targets named security_tests_timing

# Build rule for target.
security_tests_timing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 security_tests_timing
.PHONY : security_tests_timing

# fast build rule for target.
security_tests_timing/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/security_tests_timing.dir/build.make tests/security/CMakeFiles/security_tests_timing.dir/build
.PHONY : security_tests_timing/fast

#=============================================================================
# Target rules for targets named security_tests_memory

# Build rule for target.
security_tests_memory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 security_tests_memory
.PHONY : security_tests_memory

# fast build rule for target.
security_tests_memory/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/security_tests_memory.dir/build.make tests/security/CMakeFiles/security_tests_memory.dir/build
.PHONY : security_tests_memory/fast

#=============================================================================
# Target rules for targets named security_tests_crypto

# Build rule for target.
security_tests_crypto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 security_tests_crypto
.PHONY : security_tests_crypto

# fast build rule for target.
security_tests_crypto/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/security_tests_crypto.dir/build.make tests/security/CMakeFiles/security_tests_crypto.dir/build
.PHONY : security_tests_crypto/fast

#=============================================================================
# Target rules for targets named security_assessment_report

# Build rule for target.
security_assessment_report: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 security_assessment_report
.PHONY : security_assessment_report

# fast build rule for target.
security_assessment_report/fast:
	$(MAKE) $(MAKESILENT) -f tests/security/CMakeFiles/security_assessment_report.dir/build.make tests/security/CMakeFiles/security_assessment_report.dir/build
.PHONY : security_assessment_report/fast

#=============================================================================
# Target rules for targets named transport_example

# Build rule for target.
transport_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 transport_example
.PHONY : transport_example

# fast build rule for target.
transport_example/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/transport_example.dir/build.make examples/CMakeFiles/transport_example.dir/build
.PHONY : transport_example/fast

#=============================================================================
# Target rules for targets named dtls_client_example

# Build rule for target.
dtls_client_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_client_example
.PHONY : dtls_client_example

# fast build rule for target.
dtls_client_example/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/dtls_client_example.dir/build.make examples/CMakeFiles/dtls_client_example.dir/build
.PHONY : dtls_client_example/fast

#=============================================================================
# Target rules for targets named dtls_server_example

# Build rule for target.
dtls_server_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_server_example
.PHONY : dtls_server_example

# fast build rule for target.
dtls_server_example/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/dtls_server_example.dir/build.make examples/CMakeFiles/dtls_server_example.dir/build
.PHONY : dtls_server_example/fast

#=============================================================================
# Target rules for targets named dtls_connection_migration_example

# Build rule for target.
dtls_connection_migration_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_connection_migration_example
.PHONY : dtls_connection_migration_example

# fast build rule for target.
dtls_connection_migration_example/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/dtls_connection_migration_example.dir/build.make examples/CMakeFiles/dtls_connection_migration_example.dir/build
.PHONY : dtls_connection_migration_example/fast

#=============================================================================
# Target rules for targets named dtls_early_data_example

# Build rule for target.
dtls_early_data_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_early_data_example
.PHONY : dtls_early_data_example

# fast build rule for target.
dtls_early_data_example/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/dtls_early_data_example.dir/build.make examples/CMakeFiles/dtls_early_data_example.dir/build
.PHONY : dtls_early_data_example/fast

#=============================================================================
# Target rules for targets named dtls_multi_connection_server_example

# Build rule for target.
dtls_multi_connection_server_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dtls_multi_connection_server_example
.PHONY : dtls_multi_connection_server_example

# fast build rule for target.
dtls_multi_connection_server_example/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/dtls_multi_connection_server_example.dir/build.make examples/CMakeFiles/dtls_multi_connection_server_example.dir/build
.PHONY : dtls_multi_connection_server_example/fast

#=============================================================================
# Target rules for targets named run_basic_examples

# Build rule for target.
run_basic_examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_basic_examples
.PHONY : run_basic_examples

# fast build rule for target.
run_basic_examples/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/run_basic_examples.dir/build.make examples/CMakeFiles/run_basic_examples.dir/build
.PHONY : run_basic_examples/fast

#=============================================================================
# Target rules for targets named run_transport_example

# Build rule for target.
run_transport_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_transport_example
.PHONY : run_transport_example

# fast build rule for target.
run_transport_example/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/run_transport_example.dir/build.make examples/CMakeFiles/run_transport_example.dir/build
.PHONY : run_transport_example/fast

#=============================================================================
# Target rules for targets named run_client_server_demo

# Build rule for target.
run_client_server_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_client_server_demo
.PHONY : run_client_server_demo

# fast build rule for target.
run_client_server_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/run_client_server_demo.dir/build.make examples/CMakeFiles/run_client_server_demo.dir/build
.PHONY : run_client_server_demo/fast

#=============================================================================
# Target rules for targets named run_dtls_server

# Build rule for target.
run_dtls_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_dtls_server
.PHONY : run_dtls_server

# fast build rule for target.
run_dtls_server/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/run_dtls_server.dir/build.make examples/CMakeFiles/run_dtls_server.dir/build
.PHONY : run_dtls_server/fast

#=============================================================================
# Target rules for targets named run_dtls_client_interactive

# Build rule for target.
run_dtls_client_interactive: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_dtls_client_interactive
.PHONY : run_dtls_client_interactive

# fast build rule for target.
run_dtls_client_interactive/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/run_dtls_client_interactive.dir/build.make examples/CMakeFiles/run_dtls_client_interactive.dir/build
.PHONY : run_dtls_client_interactive/fast

#=============================================================================
# Target rules for targets named run_dtls_client_auto

# Build rule for target.
run_dtls_client_auto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_dtls_client_auto
.PHONY : run_dtls_client_auto

# fast build rule for target.
run_dtls_client_auto/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/run_dtls_client_auto.dir/build.make examples/CMakeFiles/run_dtls_client_auto.dir/build
.PHONY : run_dtls_client_auto/fast

#=============================================================================
# Target rules for targets named run_advanced_examples

# Build rule for target.
run_advanced_examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_advanced_examples
.PHONY : run_advanced_examples

# fast build rule for target.
run_advanced_examples/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/run_advanced_examples.dir/build.make examples/CMakeFiles/run_advanced_examples.dir/build
.PHONY : run_advanced_examples/fast

#=============================================================================
# Target rules for targets named run_migration_demo

# Build rule for target.
run_migration_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_migration_demo
.PHONY : run_migration_demo

# fast build rule for target.
run_migration_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/run_migration_demo.dir/build.make examples/CMakeFiles/run_migration_demo.dir/build
.PHONY : run_migration_demo/fast

#=============================================================================
# Target rules for targets named run_early_data_demo

# Build rule for target.
run_early_data_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_early_data_demo
.PHONY : run_early_data_demo

# fast build rule for target.
run_early_data_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/run_early_data_demo.dir/build.make examples/CMakeFiles/run_early_data_demo.dir/build
.PHONY : run_early_data_demo/fast

#=============================================================================
# Target rules for targets named run_multi_server

# Build rule for target.
run_multi_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_multi_server
.PHONY : run_multi_server

# fast build rule for target.
run_multi_server/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/run_multi_server.dir/build.make examples/CMakeFiles/run_multi_server.dir/build
.PHONY : run_multi_server/fast

#=============================================================================
# Target rules for targets named run_multi_server_custom

# Build rule for target.
run_multi_server_custom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_multi_server_custom
.PHONY : run_multi_server_custom

# fast build rule for target.
run_multi_server_custom/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/run_multi_server_custom.dir/build.make examples/CMakeFiles/run_multi_server_custom.dir/build
.PHONY : run_multi_server_custom/fast

#=============================================================================
# Target rules for targets named run_all_examples

# Build rule for target.
run_all_examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_all_examples
.PHONY : run_all_examples

# fast build rule for target.
run_all_examples/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/run_all_examples.dir/build.make examples/CMakeFiles/run_all_examples.dir/build
.PHONY : run_all_examples/fast

#=============================================================================
# Target rules for targets named examples_help

# Build rule for target.
examples_help: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 examples_help
.PHONY : examples_help

# fast build rule for target.
examples_help/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/examples_help.dir/build.make examples/CMakeFiles/examples_help.dir/build
.PHONY : examples_help/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... advanced_fuzzing_tests"
	@echo "... attack_resilience_tests"
	@echo "... attack_simulation_tests"
	@echo "... basic_side_channel_tests"
	@echo "... enhanced_side_channel_tests"
	@echo "... examples_help"
	@echo "... interop_full"
	@echo "... interop_perf"
	@echo "... interop_quick"
	@echo "... interop_report"
	@echo "... message_fuzzing_tests"
	@echo "... performance_summary"
	@echo "... protocol_fuzzing_tests"
	@echo "... rate_limiter_tests"
	@echo "... run_advanced_examples"
	@echo "... run_all_examples"
	@echo "... run_all_tests"
	@echo "... run_basic_examples"
	@echo "... run_client_server_demo"
	@echo "... run_connection_tests"
	@echo "... run_crypto_tests"
	@echo "... run_dtls_client_auto"
	@echo "... run_dtls_client_interactive"
	@echo "... run_dtls_server"
	@echo "... run_early_data_demo"
	@echo "... run_integration_tests"
	@echo "... run_interop_tests"
	@echo "... run_migration_demo"
	@echo "... run_multi_server"
	@echo "... run_multi_server_custom"
	@echo "... run_performance_benchmarks"
	@echo "... run_performance_regression"
	@echo "... run_performance_tests"
	@echo "... run_prd_validation"
	@echo "... run_protocol_tests"
	@echo "... run_reliability_tests"
	@echo "... run_security_tests"
	@echo "... run_transport_example"
	@echo "... security_assessment_report"
	@echo "... security_tests_attack_simulation"
	@echo "... security_tests_basic"
	@echo "... security_tests_comprehensive"
	@echo "... security_tests_crypto"
	@echo "... security_tests_fuzzing"
	@echo "... security_tests_memory"
	@echo "... security_tests_quick"
	@echo "... security_tests_timing"
	@echo "... side_channel_tests"
	@echo "... test_asan"
	@echo "... test_coverage"
	@echo "... test_memcheck"
	@echo "... test_report"
	@echo "... test_tsan"
	@echo "... timing_attack_tests"
	@echo "... comprehensive_security_validation"
	@echo "... dtls_advanced_fuzzing_tests"
	@echo "... dtls_attack_resilience_tests"
	@echo "... dtls_attack_simulation_tests"
	@echo "... dtls_basic_side_channel_tests"
	@echo "... dtls_basic_timing_tests"
	@echo "... dtls_client_example"
	@echo "... dtls_connection_migration_example"
	@echo "... dtls_connection_test"
	@echo "... dtls_crypto_test"
	@echo "... dtls_early_data_example"
	@echo "... dtls_enhanced_side_channel_tests"
	@echo "... dtls_integration_test"
	@echo "... dtls_interop_framework"
	@echo "... dtls_interop_test"
	@echo "... dtls_interop_tests"
	@echo "... dtls_message_fuzzing_tests"
	@echo "... dtls_multi_connection_server_example"
	@echo "... dtls_performance_test"
	@echo "... dtls_protocol_fuzzing_tests"
	@echo "... dtls_protocol_test"
	@echo "... dtls_rate_limiter_tests"
	@echo "... dtls_reliability_test"
	@echo "... dtls_security_test"
	@echo "... dtls_security_tests"
	@echo "... dtls_server_example"
	@echo "... dtls_side_channel_tests"
	@echo "... dtls_simple_side_channel_tests"
	@echo "... dtls_test_infrastructure"
	@echo "... dtls_timing_attack_tests"
	@echo "... dtls_timing_attack_tests_simple"
	@echo "... dtlsv13"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... security_report_generator"
	@echo "... transport_example"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

